name: Build and commit wheelhouse (base64, Windows)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-313:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p wheelhouse-3.13 wheelhouse-3.13-b64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Download wheels for Python 3.13 (Windows x64)
        run: |
          python -m pip download protobuf google notebook jupyter ipykernel colorama \
            --only-binary=:all: \
            --platform win_amd64 \
            --python-version 3.13 \
            --implementation cp \
            --abi cp313 \
            -d wheelhouse-3.13
          # Windows-only extras; if 3.13 wheels are missing, don't fail the job
          python -m pip download pywinpty pywin32 \
            --only-binary=:all: \
            --platform win_amd64 \
            --python-version 3.13 \
            --implementation cp \
            --abi cp313 \
            -d wheelhouse-3.13 || true

      - name: Base64-encode wheels (3.13)
        run: |
          python - <<'PY'
          import base64, pathlib
          src = pathlib.Path('wheelhouse-3.13')
          dst = pathlib.Path('wheelhouse-3.13-b64'); dst.mkdir(exist_ok=True)
          for whl in src.glob('*.whl'):
              (dst/(whl.name + '.b64')).write_bytes(base64.b64encode(whl.read_bytes()))
          PY

      - name: Add rebuild script
        run: |
          python - <<'PY'
          import textwrap, pathlib
          content = """
          import base64, pathlib, sys
          if len(sys.argv)<2 or sys.argv[1] not in ('3.13','3.12'):
              print('Usage: python rebuild_wheels.py 3.13|3.12'); raise SystemExit(1)
          v = sys.argv[1]
          src = pathlib.Path(f'wheelhouse-{v}-b64')
          dst = pathlib.Path(f'wheelhouse-{v}'); dst.mkdir(exist_ok=True)
          for b in sorted(src.glob('*.b64')):
              out = dst / b.name[:-4]
              out.write_bytes(base64.b64decode(b.read_bytes()))
              print('Wrote', out)
          print(f'\\nNow run:\\n  python -m pip install --no-index --find-links wheelhouse-{v} protobuf google notebook jupyter ipykernel colorama pywinpty pywin32')
          """
          pathlib.Path('rebuild_wheels.py').write_text(textwrap.dedent(content).strip() + '\n', encoding='utf-8')
          PY

      - name: Commit base64 wheels (3.13)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wheelhouse-3.13-b64 rebuild_wheels.py
          git commit -m "Add base64 wheelhouse for Python 3.13" || echo "Nothing to commit"
          git pull --rebase
          git push

  build-312:
    runs-on: ubuntu-latest
    needs: build-313
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p wheelhouse-3.12 wheelhouse-3.12-b64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Download wheels for Python 3.12 (Windows x64)
        run: |
          python -m pip download protobuf google notebook jupyter ipykernel colorama \
            --only-binary=:all: \
            --platform win_amd64 \
            --python-version 3.12 \
            --implementation cp \
            --abi cp312 \
            -d wheelhouse-3.12
          python -m pip download pywinpty pywin32 \
            --only-binary=:all: \
            --platform win_amd64 \
            --python-version 3.12 \
            --implementation cp \
            --abi cp312 \
            -d wheelhouse-3.12

      - name: Base64-encode wheels (3.12)
        run: |
          python - <<'PY'
          import base64, pathlib
          src = pathlib.Path('wheelhouse-3.12')
          dst = pathlib.Path('wheelhouse-3.12-b64'); dst.mkdir(exist_ok=True)
          for whl in src.glob('*.whl'):
              (dst/(whl.name + '.b64')).write_bytes(base64.b64encode(whl.read_bytes()))
          PY

      - name: Commit base64 wheels (3.12)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wheelhouse-3.12-b64
          git commit -m "Add base64 wheelhouse for Python 3.12" || echo "Nothing to commit"
          git pull --rebase
          git push
